from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("scanner", "0002_inspection_compliance_inputs")]
    operations = [
        migrations.CreateModel(name="CommodityCategory", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.CharField(max_length=80, unique=True)), ("name", models.CharField(max_length=160)), ("source_page", models.PositiveIntegerField(blank=True, null=True)), ("is_active", models.BooleanField(default=True))]),
        migrations.CreateModel(name="Exemption", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.CharField(max_length=80, unique=True)), ("description", models.TextField()), ("conditions", models.JSONField(default=dict)), ("source_page", models.PositiveIntegerField(default=24)), ("is_active", models.BooleanField(default=True))]),
        migrations.CreateModel(name="Rule", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("rule_number", models.CharField(max_length=20)), ("sub_rule", models.CharField(blank=True, max_length=40)), ("title", models.CharField(max_length=255)), ("requirement", models.TextField()), ("applicability_condition", models.TextField(blank=True)), ("validation_type", models.CharField(default="MANUAL_REVIEW", max_length=80)), ("validation_config", models.JSONField(blank=True, default=dict)), ("severity", models.CharField(default="WARNING", max_length=20)), ("source_document", models.CharField(default="The Legal Metrology (Packaged Commodities) Rules, 2011.pdf", max_length=255)), ("source_page", models.CharField(blank=True, max_length=40)), ("source_reference", models.CharField(blank=True, max_length=255)), ("schedule_reference", models.CharField(blank=True, max_length=80)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))], options={"ordering":["rule_number","sub_rule"]}),
        migrations.CreateModel(name="ScheduleEntry", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("schedule", models.CharField(choices=[("FIRST","First Schedule"),("THIRD","Third Schedule"),("FOURTH","Fourth Schedule")], max_length=10)), ("commodity", models.CharField(max_length=180)), ("data", models.JSONField(default=dict)), ("source_page", models.PositiveIntegerField()), ("source_reference", models.CharField(blank=True, max_length=255))]),
        migrations.CreateModel(name="StandardPackSize", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("quantity_value", models.DecimalField(decimal_places=3, max_digits=12)), ("quantity_unit", models.CharField(max_length=20)), ("conditions", models.TextField(blank=True)), ("rule_reference", models.CharField(default="Rule 5", max_length=40)), ("schedule_reference", models.CharField(default="Second Schedule", max_length=80)), ("source_page", models.PositiveIntegerField(default=29)), ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="standard_pack_sizes", to="compliance.commoditycategory"))]),
        migrations.CreateModel(name="ComplianceEvaluation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("overall_status", models.CharField(choices=[("COMPLIANT","Compliant"),("NON_COMPLIANT","Non-compliant"),("NEEDS_MANUAL_REVIEW","Needs manual review"),("INCONCLUSIVE","Inconclusive")], default="INCONCLUSIVE", max_length=30)), ("total_rules", models.PositiveIntegerField(default=0)), ("passed", models.PositiveIntegerField(default=0)), ("failed", models.PositiveIntegerField(default=0)), ("warnings", models.PositiveIntegerField(default=0)), ("manual_review", models.PositiveIntegerField(default=0)), ("not_applicable", models.PositiveIntegerField(default=0)), ("evaluated_at", models.DateTimeField(auto_now=True)), ("inspection", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="compliance_evaluation", to="scanner.inspection"))]),
        migrations.CreateModel(name="ComplianceResult", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("PASS","Pass"),("FAIL","Fail"),("WARNING","Warning"),("MANUAL_REVIEW","Manual review"),("NOT_APPLICABLE","Not applicable"),("NOT_DETECTED","Not detected")], max_length=20)), ("detected_value", models.TextField(blank=True)), ("expected_requirement", models.TextField(blank=True)), ("evidence", models.JSONField(blank=True, default=dict)), ("source_ocr_field", models.CharField(blank=True, max_length=100)), ("severity", models.CharField(default="WARNING", max_length=20)), ("explanation", models.TextField(blank=True)), ("recommendation", models.TextField(blank=True)), ("evaluated_at", models.DateTimeField(auto_now=True)), ("evaluation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="results", to="compliance.complianceevaluation")), ("rule", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="compliance_results", to="compliance.rule")), ("source_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="scanner.inspectionimage"))]),
        migrations.AddConstraint(model_name="rule", constraint=models.UniqueConstraint(fields=("rule_number","sub_rule"), name="unique_rule_reference")),
    ]
