# Generated by Django 5.2.17 on 2026-09-05 08:18

import django.db.models.deletion
import scanner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('OCR_COMPLETE', 'OCR complete'), ('EXTRACTION_COMPLETE', 'Extraction complete'), ('AWAITING_VERIFICATION', 'Awaiting verification'), ('VERIFIED', 'Verified'), ('READY_FOR_COMPLIANCE', 'Ready for compliance'), ('FAILED', 'Failed')], default='CREATED', max_length=32)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict)),
                ('original_values', models.JSONField(blank=True, default=dict)),
                ('field_metadata', models.JSONField(blank=True, default=dict)),
                ('verification_status', models.CharField(choices=[('DETECTED', 'Detected'), ('NOT_DETECTED', 'Not detected'), ('LOW_CONFIDENCE', 'Low confidence'), ('VERIFIED', 'Verified'), ('CORRECTED', 'Corrected')], default='DETECTED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_product_data', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='scanner.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=scanner.models.inspection_image_path)),
                ('processed_image', models.ImageField(blank=True, upload_to=scanner.models.processed_image_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('image_order', models.PositiveIntegerField(default=0)),
                ('image_type', models.CharField(choices=[('FRONT', 'Front'), ('BACK', 'Back'), ('SIDE', 'Side'), ('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('quality_warning', models.CharField(blank=True, max_length=255)),
                ('processing_status', models.CharField(default='UPLOADED', max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scanner.inspection')),
            ],
            options={
                'ordering': ['image_order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('average_confidence', models.FloatField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('engine_version', models.CharField(blank=True, max_length=50)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='scanner.inspectionimage')),
            ],
        ),
    ]
