from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, PageBreak


DISCLAIMER = (
    "This report is generated by the Legal Metrology compliance inspection system as a "
    "decision-support/preliminary inspection aid. Automated results are based on available "
    "image/OCR data and configured legal rules. Where physical measurement or manual "
    "verification is required, the officer must perform the appropriate inspection."
)


def _text(value):
    if value in (None, ""):
        return "Not Detected"
    return str(value).encode("ascii", "replace").decode("ascii")


def _paragraph(value, style):
    return Paragraph(_text(value).replace("&", "&amp;").replace("<", "&lt;"), style)


def _table(rows, widths, styles):
    table = Table(rows, colWidths=widths, repeatRows=1)
    table.setStyle(TableStyle(styles))
    return table


def build_inspection_report(inspection):
    """Build a PDF from persisted inspection data without running processing again."""
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
        title=f"Legal Metrology Inspection Report {inspection.inspection_id}",
    )
    styles = getSampleStyleSheet()
    title = ParagraphStyle("ReportTitle", parent=styles["Title"], alignment=TA_CENTER, fontSize=16, leading=20, spaceAfter=4)
    subtitle = ParagraphStyle("ReportSubtitle", parent=styles["Normal"], alignment=TA_CENTER, fontSize=10, leading=13, spaceAfter=12)
    heading = ParagraphStyle("ReportHeading", parent=styles["Heading2"], fontSize=12, leading=15, spaceBefore=10, spaceAfter=6, textColor=colors.HexColor("#17324d"))
    body = ParagraphStyle("ReportBody", parent=styles["BodyText"], fontSize=8.5, leading=11)
    small = ParagraphStyle("ReportSmall", parent=body, fontSize=7.5, leading=9)
    cell = ParagraphStyle("ReportCell", parent=body, fontSize=8, leading=10)

    profile = getattr(inspection.officer, "officer_profile", None)
    evaluation = inspection.compliance_evaluations.filter(is_current=True).prefetch_related("results__rule", "results__source_image").first()
    extracted = getattr(inspection, "extracted_data", None)
    story = [
        _paragraph("LEGAL METROLOGY", title),
        _paragraph("PACKAGED COMMODITIES", title),
        _paragraph("COMPLIANCE INSPECTION REPORT", title),
        _paragraph(f"Inspection ID: {inspection.inspection_id}", subtitle),
    ]

    officer_name = getattr(profile, "name", "Not recorded")
    officer_rows = [
        [_paragraph("Report details", cell), _paragraph("Officer details", cell)],
        [_paragraph(f"Inspection ID: {inspection.inspection_id}<br/>Date: {inspection.created_at:%Y-%m-%d %H:%M %Z}<br/>Status: {inspection.status}", cell),
         _paragraph(f"Name: {officer_name}<br/>Officer ID: {getattr(profile, 'officer_id', 'Not recorded')}<br/>Designation: {getattr(profile, 'designation', 'Not recorded')}<br/>Department: {getattr(profile, 'department', 'Not recorded')}<br/>Jurisdiction: {getattr(profile, 'jurisdiction', 'Not recorded')}", cell)],
    ]
    story.append(_table(officer_rows, [85 * mm, 85 * mm], [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dceaf4")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#9aabb8")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))

    story.append(_paragraph("INSPECTION SUMMARY", heading))
    overall = evaluation.overall_status if evaluation else "INCONCLUSIVE"
    summary = [
        [_paragraph("Field", cell), _paragraph("Value", cell)],
        [_paragraph("Product name", cell), _paragraph(inspection.product_name, cell)],
        [_paragraph("Package images", cell), _paragraph(inspection.images.count(), cell)],
        [_paragraph("Inspection date", cell), _paragraph(inspection.created_at, cell)],
        [_paragraph("Overall compliance status", cell), _paragraph(overall, cell)],
    ]
    story.append(_table(summary, [55 * mm, 115 * mm], [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dceaf4")), ("GRID", (0, 0), (-1, -1), 0.4, colors.grey), ("PADDING", (0, 0), (-1, -1), 5)]))

    story.append(_paragraph("PACKAGE INFORMATION", heading))
    package_rows = [[_paragraph("Field", cell), _paragraph("Value", cell), _paragraph("Verification", cell)]]
    values = (extracted.values if extracted else {}) or {}
    metadata = (extracted.field_metadata if extracted else {}) or {}
    fields = [
        ("Product name", inspection.product_name or values.get("product_name")), ("Common/generic name", values.get("common_or_generic_name")),
        ("Manufacturer", values.get("manufacturer_name")), ("Manufacturer address", values.get("manufacturer_address")),
        ("Packer", values.get("packer_name")), ("Packer address", values.get("packer_address")),
        ("Importer", values.get("importer_name")), ("Importer address", values.get("importer_address")),
        ("Country of origin", values.get("country_of_origin")), ("Net quantity", values.get("net_quantity")),
        ("Quantity unit", values.get("quantity_unit") or inspection.quantity_unit), ("MRP / retail sale price", values.get("mrp")),
        ("Manufacturing/packing date", values.get("manufacturing_date") or values.get("packing_date")), ("Best before/use by", values.get("best_before") or values.get("use_by")),
        ("Consumer care/contact", values.get("consumer_care_name") or values.get("consumer_care_phone") or values.get("consumer_care_email")), ("Unit sale price", values.get("unit_sale_price")),
        ("Dimensions", values.get("dimensions")), ("Batch/lot number", values.get("batch_number")),
    ]
    for label, value in fields:
        metadata_key = {"Product name": "product_name", "Common/generic name": "common_or_generic_name", "Manufacturer": "manufacturer_name", "Packer": "packer_name", "Importer": "importer_name", "Manufacturing/packing date": "manufacturing_date", "Consumer care/contact": "consumer_care_name"}.get(label, label.lower().replace(" ", "_"))
        field_status = metadata.get(metadata_key, {}).get("status", getattr(extracted, "verification_status", "NOT_DETECTED")) if extracted else "NOT_DETECTED"
        package_rows.append([_paragraph(label, cell), _paragraph(value, cell), _paragraph(field_status, cell)])
    story.append(_table(package_rows, [48 * mm, 85 * mm, 37 * mm], [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dceaf4")), ("GRID", (0, 0), (-1, -1), 0.35, colors.grey), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 4)]))

    story.append(_paragraph("COMPLIANCE RESULTS", heading))
    if evaluation:
        story.append(_paragraph(f"Evaluation version {evaluation.evaluation_version}, evaluated {evaluation.evaluated_at}. Pass: {evaluation.passed}; Fail: {evaluation.failed}; Manual review: {evaluation.manual_review}; Not applicable: {evaluation.not_applicable}.", body))
        result_rows = [[_paragraph("Rule", cell), _paragraph("Status", cell), _paragraph("Detected / requirement", cell), _paragraph("Explanation / recommendation / evidence", cell)]]
        manual_items = []
        for result in evaluation.results.all():
            rule = result.rule
            evidence = result.evidence or {}
            evidence_text = f"Evidence: {_text(evidence)}<br/>Source image: {getattr(result.source_image, 'id', 'Not recorded')}"
            result_rows.append([_paragraph(f"{rule.rule_number} {rule.title}", cell), _paragraph(result.status, cell), _paragraph(f"Detected: {result.detected_value}<br/>Requirement: {result.expected_requirement or rule.requirement}", cell), _paragraph(f"{result.explanation}<br/>Recommendation: {result.recommendation}<br/>{evidence_text}", small)])
            if result.status in {"MANUAL_REVIEW", "NOT_DETECTED", "WARNING"}:
                manual_items.append((rule, result))
        story.append(_table(result_rows, [32 * mm, 25 * mm, 55 * mm, 58 * mm], [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dceaf4")), ("GRID", (0, 0), (-1, -1), 0.35, colors.grey), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 4)]))
    else:
        story.append(_paragraph("No current compliance evaluation is available. Overall status is INCONCLUSIVE.", body))
        manual_items = []

    story.append(_paragraph("MANUAL VERIFICATION REQUIRED", heading))
    if manual_items:
        for rule, result in manual_items:
            story.append(_paragraph(f"Rule {rule.rule_number} - {rule.title}: {result.explanation or result.status}. Verify: {result.recommendation or rule.requirement}. Current evidence: {result.evidence or 'None recorded.'}", body))
            story.append(Spacer(1, 3))
    else:
        story.append(_paragraph("No persisted rule result currently requires manual verification.", body))
    story.append(_paragraph("Image/OCR analysis cannot replace physical inspection where physical measurement, letter height, dimensions, or quantity/MPE verification is required.", body))

    story.append(_paragraph("EVIDENCE AND AUDIT TRAIL", heading))
    for image in inspection.images.all():
        story.append(_paragraph(f"Image {image.id}: {image.original_filename}; source image identifier; OCR: {getattr(getattr(image, 'ocr_result', None), 'raw_text', '') or 'Not available'}", small))
    for audit in inspection.audit_logs.all():
        story.append(_paragraph(f"{audit.timestamp:%Y-%m-%d %H:%M} - {audit.action}: {audit.description}", small))
    for correction in inspection.corrections.all():
        story.append(_paragraph(f"Correction {correction.field_name}: {correction.original_value} -> {correction.corrected_value}; officer: {getattr(correction.corrected_by.officer_profile, 'name', correction.corrected_by.username)}; {correction.created_at:%Y-%m-%d %H:%M}", small))

    story.append(_paragraph("DISCLAIMER", heading))
    story.append(_paragraph(DISCLAIMER, body))
    document.build(story)
    return buffer.getvalue()