# Generated by Django 5.2.17 on 2026-09-04 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.CharField(db_index=True, help_text='Unique official ID issued to the officer (e.g., OFF-DEL-2024-001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Official full name of the officer', max_length=150)),
                ('designation', models.CharField(help_text='Official designation (e.g., Senior Inspector of Legal Metrology)', max_length=100)),
                ('department', models.CharField(default='Department of Consumer Affairs, Legal Metrology Division', help_text='Department or directorate', max_length=200)),
                ('jurisdiction', models.CharField(help_text='Jurisdiction or assigned enforcement zone (e.g., Zone-1, Central Delhi)', max_length=150)),
                ('role', models.CharField(choices=[('ADMIN', 'Department Administrator'), ('INSPECTOR', 'Legal Metrology Inspector')], default='INSPECTOR', help_text='Role defining system permissions', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Official contact phone number', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this officer profile is authorized to perform inspections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Auth User')),
            ],
            options={
                'verbose_name': 'Officer Profile',
                'verbose_name_plural': 'Officer Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
